/*
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SimpleJavaUiModule extends AbstractSimpleJavaUiModule {

	public SimpleJavaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
