/**
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.simpleJava;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.common.types.JvmParameterizedTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Param</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleParam#getParamType <em>Param Type</em>}</li>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleParam#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleParam()
 * @model
 * @generated
 */
public interface SimpleParam extends EObject
{
  /**
   * Returns the value of the '<em><b>Param Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Type</em>' containment reference.
   * @see #setParamType(JvmParameterizedTypeReference)
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleParam_ParamType()
   * @model containment="true"
   * @generated
   */
  JvmParameterizedTypeReference getParamType();

  /**
   * Sets the value of the '{@link org.xtext.simplejava.simpleJava.SimpleParam#getParamType <em>Param Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param Type</em>' containment reference.
   * @see #getParamType()
   * @generated
   */
  void setParamType(JvmParameterizedTypeReference value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleParam_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.simplejava.simpleJava.SimpleParam#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // SimpleParam
