/**
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.simpleJava;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.common.types.JvmParameterizedTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleField#getAccessType <em>Access Type</em>}</li>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleField#isIsStatic <em>Is Static</em>}</li>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleField#isIsFinal <em>Is Final</em>}</li>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleField#getFieldType <em>Field Type</em>}</li>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleField#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleField()
 * @model
 * @generated
 */
public interface SimpleField extends EObject
{
  /**
   * Returns the value of the '<em><b>Access Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Access Type</em>' attribute.
   * @see #setAccessType(String)
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleField_AccessType()
   * @model
   * @generated
   */
  String getAccessType();

  /**
   * Sets the value of the '{@link org.xtext.simplejava.simpleJava.SimpleField#getAccessType <em>Access Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Access Type</em>' attribute.
   * @see #getAccessType()
   * @generated
   */
  void setAccessType(String value);

  /**
   * Returns the value of the '<em><b>Is Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Static</em>' attribute.
   * @see #setIsStatic(boolean)
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleField_IsStatic()
   * @model
   * @generated
   */
  boolean isIsStatic();

  /**
   * Sets the value of the '{@link org.xtext.simplejava.simpleJava.SimpleField#isIsStatic <em>Is Static</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Static</em>' attribute.
   * @see #isIsStatic()
   * @generated
   */
  void setIsStatic(boolean value);

  /**
   * Returns the value of the '<em><b>Is Final</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Final</em>' attribute.
   * @see #setIsFinal(boolean)
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleField_IsFinal()
   * @model
   * @generated
   */
  boolean isIsFinal();

  /**
   * Sets the value of the '{@link org.xtext.simplejava.simpleJava.SimpleField#isIsFinal <em>Is Final</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Final</em>' attribute.
   * @see #isIsFinal()
   * @generated
   */
  void setIsFinal(boolean value);

  /**
   * Returns the value of the '<em><b>Field Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Type</em>' containment reference.
   * @see #setFieldType(JvmParameterizedTypeReference)
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleField_FieldType()
   * @model containment="true"
   * @generated
   */
  JvmParameterizedTypeReference getFieldType();

  /**
   * Sets the value of the '{@link org.xtext.simplejava.simpleJava.SimpleField#getFieldType <em>Field Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Type</em>' containment reference.
   * @see #getFieldType()
   * @generated
   */
  void setFieldType(JvmParameterizedTypeReference value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleField_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.simplejava.simpleJava.SimpleField#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // SimpleField
