/**
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.simpleJava;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleMethod#getAccessType <em>Access Type</em>}</li>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleMethod#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleMethod#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleMethod()
 * @model
 * @generated
 */
public interface SimpleMethod extends EObject
{
  /**
   * Returns the value of the '<em><b>Access Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Access Type</em>' attribute.
   * @see #setAccessType(String)
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleMethod_AccessType()
   * @model
   * @generated
   */
  String getAccessType();

  /**
   * Sets the value of the '{@link org.xtext.simplejava.simpleJava.SimpleMethod#getAccessType <em>Access Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Access Type</em>' attribute.
   * @see #getAccessType()
   * @generated
   */
  void setAccessType(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleMethod_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.simplejava.simpleJava.SimpleMethod#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.simplejava.simpleJava.SimpleParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleMethod_Params()
   * @model containment="true"
   * @generated
   */
  EList<SimpleParam> getParams();

} // SimpleMethod
