/**
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.simpleJava;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage
 * @generated
 */
public interface SimpleJavaFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimpleJavaFactory eINSTANCE = org.xtext.simplejava.simpleJava.impl.SimpleJavaFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Simple Package</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Package</em>'.
   * @generated
   */
  SimplePackage createSimplePackage();

  /**
   * Returns a new object of class '<em>Simple Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Class</em>'.
   * @generated
   */
  SimpleClass createSimpleClass();

  /**
   * Returns a new object of class '<em>Simple Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Field</em>'.
   * @generated
   */
  SimpleField createSimpleField();

  /**
   * Returns a new object of class '<em>Simple Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Method</em>'.
   * @generated
   */
  SimpleMethod createSimpleMethod();

  /**
   * Returns a new object of class '<em>Simple Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Param</em>'.
   * @generated
   */
  SimpleParam createSimpleParam();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SimpleJavaPackage getSimpleJavaPackage();

} //SimpleJavaFactory
