/**
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.simpleJava;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.simplejava.simpleJava.SimpleJavaFactory
 * @model kind="package"
 * @generated
 */
public interface SimpleJavaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "simpleJava";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/simplejava/SimpleJava";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "simpleJava";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimpleJavaPackage eINSTANCE = org.xtext.simplejava.simpleJava.impl.SimpleJavaPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.simplejava.simpleJava.impl.SimplePackageImpl <em>Simple Package</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplejava.simpleJava.impl.SimplePackageImpl
   * @see org.xtext.simplejava.simpleJava.impl.SimpleJavaPackageImpl#getSimplePackage()
   * @generated
   */
  int SIMPLE_PACKAGE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_PACKAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Simple Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_PACKAGE__SIMPLE_CLASSES = 1;

  /**
   * The number of structural features of the '<em>Simple Package</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_PACKAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.simplejava.simpleJava.impl.SimpleClassImpl <em>Simple Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplejava.simpleJava.impl.SimpleClassImpl
   * @see org.xtext.simplejava.simpleJava.impl.SimpleJavaPackageImpl#getSimpleClass()
   * @generated
   */
  int SIMPLE_CLASS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_CLASS__NAME = 0;

  /**
   * The feature id for the '<em><b>Simple Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_CLASS__SIMPLE_FIELDS = 1;

  /**
   * The feature id for the '<em><b>Simple Methods</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_CLASS__SIMPLE_METHODS = 2;

  /**
   * The number of structural features of the '<em>Simple Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_CLASS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.simplejava.simpleJava.impl.SimpleFieldImpl <em>Simple Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplejava.simpleJava.impl.SimpleFieldImpl
   * @see org.xtext.simplejava.simpleJava.impl.SimpleJavaPackageImpl#getSimpleField()
   * @generated
   */
  int SIMPLE_FIELD = 2;

  /**
   * The feature id for the '<em><b>Access Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FIELD__ACCESS_TYPE = 0;

  /**
   * The feature id for the '<em><b>Is Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FIELD__IS_STATIC = 1;

  /**
   * The feature id for the '<em><b>Is Final</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FIELD__IS_FINAL = 2;

  /**
   * The feature id for the '<em><b>Field Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FIELD__FIELD_TYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FIELD__NAME = 4;

  /**
   * The number of structural features of the '<em>Simple Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FIELD_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.simplejava.simpleJava.impl.SimpleMethodImpl <em>Simple Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplejava.simpleJava.impl.SimpleMethodImpl
   * @see org.xtext.simplejava.simpleJava.impl.SimpleJavaPackageImpl#getSimpleMethod()
   * @generated
   */
  int SIMPLE_METHOD = 3;

  /**
   * The feature id for the '<em><b>Access Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_METHOD__ACCESS_TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_METHOD__NAME = 1;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_METHOD__PARAMS = 2;

  /**
   * The number of structural features of the '<em>Simple Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_METHOD_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.simplejava.simpleJava.impl.SimpleParamImpl <em>Simple Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplejava.simpleJava.impl.SimpleParamImpl
   * @see org.xtext.simplejava.simpleJava.impl.SimpleJavaPackageImpl#getSimpleParam()
   * @generated
   */
  int SIMPLE_PARAM = 4;

  /**
   * The feature id for the '<em><b>Param Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_PARAM__PARAM_TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_PARAM__NAME = 1;

  /**
   * The number of structural features of the '<em>Simple Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_PARAM_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.simplejava.simpleJava.SimplePackage <em>Simple Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Package</em>'.
   * @see org.xtext.simplejava.simpleJava.SimplePackage
   * @generated
   */
  EClass getSimplePackage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplejava.simpleJava.SimplePackage#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.simplejava.simpleJava.SimplePackage#getName()
   * @see #getSimplePackage()
   * @generated
   */
  EAttribute getSimplePackage_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.simplejava.simpleJava.SimplePackage#getSimpleClasses <em>Simple Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Simple Classes</em>'.
   * @see org.xtext.simplejava.simpleJava.SimplePackage#getSimpleClasses()
   * @see #getSimplePackage()
   * @generated
   */
  EReference getSimplePackage_SimpleClasses();

  /**
   * Returns the meta object for class '{@link org.xtext.simplejava.simpleJava.SimpleClass <em>Simple Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Class</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleClass
   * @generated
   */
  EClass getSimpleClass();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplejava.simpleJava.SimpleClass#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleClass#getName()
   * @see #getSimpleClass()
   * @generated
   */
  EAttribute getSimpleClass_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.simplejava.simpleJava.SimpleClass#getSimpleFields <em>Simple Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Simple Fields</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleClass#getSimpleFields()
   * @see #getSimpleClass()
   * @generated
   */
  EReference getSimpleClass_SimpleFields();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.simplejava.simpleJava.SimpleClass#getSimpleMethods <em>Simple Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Simple Methods</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleClass#getSimpleMethods()
   * @see #getSimpleClass()
   * @generated
   */
  EReference getSimpleClass_SimpleMethods();

  /**
   * Returns the meta object for class '{@link org.xtext.simplejava.simpleJava.SimpleField <em>Simple Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Field</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleField
   * @generated
   */
  EClass getSimpleField();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplejava.simpleJava.SimpleField#getAccessType <em>Access Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Access Type</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleField#getAccessType()
   * @see #getSimpleField()
   * @generated
   */
  EAttribute getSimpleField_AccessType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplejava.simpleJava.SimpleField#isIsStatic <em>Is Static</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Static</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleField#isIsStatic()
   * @see #getSimpleField()
   * @generated
   */
  EAttribute getSimpleField_IsStatic();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplejava.simpleJava.SimpleField#isIsFinal <em>Is Final</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Final</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleField#isIsFinal()
   * @see #getSimpleField()
   * @generated
   */
  EAttribute getSimpleField_IsFinal();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.simplejava.simpleJava.SimpleField#getFieldType <em>Field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Field Type</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleField#getFieldType()
   * @see #getSimpleField()
   * @generated
   */
  EReference getSimpleField_FieldType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplejava.simpleJava.SimpleField#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleField#getName()
   * @see #getSimpleField()
   * @generated
   */
  EAttribute getSimpleField_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.simplejava.simpleJava.SimpleMethod <em>Simple Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Method</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleMethod
   * @generated
   */
  EClass getSimpleMethod();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplejava.simpleJava.SimpleMethod#getAccessType <em>Access Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Access Type</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleMethod#getAccessType()
   * @see #getSimpleMethod()
   * @generated
   */
  EAttribute getSimpleMethod_AccessType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplejava.simpleJava.SimpleMethod#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleMethod#getName()
   * @see #getSimpleMethod()
   * @generated
   */
  EAttribute getSimpleMethod_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.simplejava.simpleJava.SimpleMethod#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleMethod#getParams()
   * @see #getSimpleMethod()
   * @generated
   */
  EReference getSimpleMethod_Params();

  /**
   * Returns the meta object for class '{@link org.xtext.simplejava.simpleJava.SimpleParam <em>Simple Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Param</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleParam
   * @generated
   */
  EClass getSimpleParam();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.simplejava.simpleJava.SimpleParam#getParamType <em>Param Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Param Type</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleParam#getParamType()
   * @see #getSimpleParam()
   * @generated
   */
  EReference getSimpleParam_ParamType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplejava.simpleJava.SimpleParam#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.simplejava.simpleJava.SimpleParam#getName()
   * @see #getSimpleParam()
   * @generated
   */
  EAttribute getSimpleParam_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SimpleJavaFactory getSimpleJavaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.simplejava.simpleJava.impl.SimplePackageImpl <em>Simple Package</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplejava.simpleJava.impl.SimplePackageImpl
     * @see org.xtext.simplejava.simpleJava.impl.SimpleJavaPackageImpl#getSimplePackage()
     * @generated
     */
    EClass SIMPLE_PACKAGE = eINSTANCE.getSimplePackage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_PACKAGE__NAME = eINSTANCE.getSimplePackage_Name();

    /**
     * The meta object literal for the '<em><b>Simple Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_PACKAGE__SIMPLE_CLASSES = eINSTANCE.getSimplePackage_SimpleClasses();

    /**
     * The meta object literal for the '{@link org.xtext.simplejava.simpleJava.impl.SimpleClassImpl <em>Simple Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplejava.simpleJava.impl.SimpleClassImpl
     * @see org.xtext.simplejava.simpleJava.impl.SimpleJavaPackageImpl#getSimpleClass()
     * @generated
     */
    EClass SIMPLE_CLASS = eINSTANCE.getSimpleClass();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_CLASS__NAME = eINSTANCE.getSimpleClass_Name();

    /**
     * The meta object literal for the '<em><b>Simple Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_CLASS__SIMPLE_FIELDS = eINSTANCE.getSimpleClass_SimpleFields();

    /**
     * The meta object literal for the '<em><b>Simple Methods</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_CLASS__SIMPLE_METHODS = eINSTANCE.getSimpleClass_SimpleMethods();

    /**
     * The meta object literal for the '{@link org.xtext.simplejava.simpleJava.impl.SimpleFieldImpl <em>Simple Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplejava.simpleJava.impl.SimpleFieldImpl
     * @see org.xtext.simplejava.simpleJava.impl.SimpleJavaPackageImpl#getSimpleField()
     * @generated
     */
    EClass SIMPLE_FIELD = eINSTANCE.getSimpleField();

    /**
     * The meta object literal for the '<em><b>Access Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_FIELD__ACCESS_TYPE = eINSTANCE.getSimpleField_AccessType();

    /**
     * The meta object literal for the '<em><b>Is Static</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_FIELD__IS_STATIC = eINSTANCE.getSimpleField_IsStatic();

    /**
     * The meta object literal for the '<em><b>Is Final</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_FIELD__IS_FINAL = eINSTANCE.getSimpleField_IsFinal();

    /**
     * The meta object literal for the '<em><b>Field Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_FIELD__FIELD_TYPE = eINSTANCE.getSimpleField_FieldType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_FIELD__NAME = eINSTANCE.getSimpleField_Name();

    /**
     * The meta object literal for the '{@link org.xtext.simplejava.simpleJava.impl.SimpleMethodImpl <em>Simple Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplejava.simpleJava.impl.SimpleMethodImpl
     * @see org.xtext.simplejava.simpleJava.impl.SimpleJavaPackageImpl#getSimpleMethod()
     * @generated
     */
    EClass SIMPLE_METHOD = eINSTANCE.getSimpleMethod();

    /**
     * The meta object literal for the '<em><b>Access Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_METHOD__ACCESS_TYPE = eINSTANCE.getSimpleMethod_AccessType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_METHOD__NAME = eINSTANCE.getSimpleMethod_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_METHOD__PARAMS = eINSTANCE.getSimpleMethod_Params();

    /**
     * The meta object literal for the '{@link org.xtext.simplejava.simpleJava.impl.SimpleParamImpl <em>Simple Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplejava.simpleJava.impl.SimpleParamImpl
     * @see org.xtext.simplejava.simpleJava.impl.SimpleJavaPackageImpl#getSimpleParam()
     * @generated
     */
    EClass SIMPLE_PARAM = eINSTANCE.getSimpleParam();

    /**
     * The meta object literal for the '<em><b>Param Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_PARAM__PARAM_TYPE = eINSTANCE.getSimpleParam_ParamType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_PARAM__NAME = eINSTANCE.getSimpleParam_Name();

  }

} //SimpleJavaPackage
