/**
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.simpleJava;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleClass#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleClass#getSimpleFields <em>Simple Fields</em>}</li>
 *   <li>{@link org.xtext.simplejava.simpleJava.SimpleClass#getSimpleMethods <em>Simple Methods</em>}</li>
 * </ul>
 *
 * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleClass()
 * @model
 * @generated
 */
public interface SimpleClass extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleClass_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.simplejava.simpleJava.SimpleClass#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Simple Fields</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.simplejava.simpleJava.SimpleField}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple Fields</em>' containment reference list.
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleClass_SimpleFields()
   * @model containment="true"
   * @generated
   */
  EList<SimpleField> getSimpleFields();

  /**
   * Returns the value of the '<em><b>Simple Methods</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.simplejava.simpleJava.SimpleMethod}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple Methods</em>' containment reference list.
   * @see org.xtext.simplejava.simpleJava.SimpleJavaPackage#getSimpleClass_SimpleMethods()
   * @model containment="true"
   * @generated
   */
  EList<SimpleMethod> getSimpleMethods();

} // SimpleClass
