/*
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SimpleJavaStandaloneSetup extends SimpleJavaStandaloneSetupGenerated {

	public static void doSetup() {
		new SimpleJavaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
