/*
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.simplejava.ui.internal.SimplejavaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimpleJavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SimplejavaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SimplejavaActivator activator = SimplejavaActivator.getInstance();
		return activator != null ? activator.getInjector(SimplejavaActivator.ORG_XTEXT_SIMPLEJAVA_SIMPLEJAVA) : null;
	}

}
