/*
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractSimpleJavaScopeProvider extends XbaseBatchScopeProvider {
}
