/**
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.simpleJava.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.simplejava.simpleJava.SimpleClass;
import org.xtext.simplejava.simpleJava.SimpleField;
import org.xtext.simplejava.simpleJava.SimpleJavaPackage;
import org.xtext.simplejava.simpleJava.SimpleMethod;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Class</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.simplejava.simpleJava.impl.SimpleClassImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.simplejava.simpleJava.impl.SimpleClassImpl#getSimpleFields <em>Simple Fields</em>}</li>
 *   <li>{@link org.xtext.simplejava.simpleJava.impl.SimpleClassImpl#getSimpleMethods <em>Simple Methods</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SimpleClassImpl extends MinimalEObjectImpl.Container implements SimpleClass
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getSimpleFields() <em>Simple Fields</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimpleFields()
   * @generated
   * @ordered
   */
  protected EList<SimpleField> simpleFields;

  /**
   * The cached value of the '{@link #getSimpleMethods() <em>Simple Methods</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimpleMethods()
   * @generated
   * @ordered
   */
  protected EList<SimpleMethod> simpleMethods;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleClassImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimpleJavaPackage.Literals.SIMPLE_CLASS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimpleJavaPackage.SIMPLE_CLASS__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SimpleField> getSimpleFields()
  {
    if (simpleFields == null)
    {
      simpleFields = new EObjectContainmentEList<SimpleField>(SimpleField.class, this, SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_FIELDS);
    }
    return simpleFields;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SimpleMethod> getSimpleMethods()
  {
    if (simpleMethods == null)
    {
      simpleMethods = new EObjectContainmentEList<SimpleMethod>(SimpleMethod.class, this, SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_METHODS);
    }
    return simpleMethods;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_FIELDS:
        return ((InternalEList<?>)getSimpleFields()).basicRemove(otherEnd, msgs);
      case SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_METHODS:
        return ((InternalEList<?>)getSimpleMethods()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SimpleJavaPackage.SIMPLE_CLASS__NAME:
        return getName();
      case SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_FIELDS:
        return getSimpleFields();
      case SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_METHODS:
        return getSimpleMethods();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SimpleJavaPackage.SIMPLE_CLASS__NAME:
        setName((String)newValue);
        return;
      case SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_FIELDS:
        getSimpleFields().clear();
        getSimpleFields().addAll((Collection<? extends SimpleField>)newValue);
        return;
      case SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_METHODS:
        getSimpleMethods().clear();
        getSimpleMethods().addAll((Collection<? extends SimpleMethod>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SimpleJavaPackage.SIMPLE_CLASS__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_FIELDS:
        getSimpleFields().clear();
        return;
      case SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_METHODS:
        getSimpleMethods().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SimpleJavaPackage.SIMPLE_CLASS__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_FIELDS:
        return simpleFields != null && !simpleFields.isEmpty();
      case SimpleJavaPackage.SIMPLE_CLASS__SIMPLE_METHODS:
        return simpleMethods != null && !simpleMethods.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //SimpleClassImpl
