/**
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.simpleJava.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.simplejava.simpleJava.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SimpleJavaFactoryImpl extends EFactoryImpl implements SimpleJavaFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static SimpleJavaFactory init()
  {
    try
    {
      SimpleJavaFactory theSimpleJavaFactory = (SimpleJavaFactory)EPackage.Registry.INSTANCE.getEFactory(SimpleJavaPackage.eNS_URI);
      if (theSimpleJavaFactory != null)
      {
        return theSimpleJavaFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new SimpleJavaFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SimpleJavaFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case SimpleJavaPackage.SIMPLE_PACKAGE: return createSimplePackage();
      case SimpleJavaPackage.SIMPLE_CLASS: return createSimpleClass();
      case SimpleJavaPackage.SIMPLE_FIELD: return createSimpleField();
      case SimpleJavaPackage.SIMPLE_METHOD: return createSimpleMethod();
      case SimpleJavaPackage.SIMPLE_PARAM: return createSimpleParam();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SimplePackage createSimplePackage()
  {
    SimplePackageImpl simplePackage = new SimplePackageImpl();
    return simplePackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SimpleClass createSimpleClass()
  {
    SimpleClassImpl simpleClass = new SimpleClassImpl();
    return simpleClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SimpleField createSimpleField()
  {
    SimpleFieldImpl simpleField = new SimpleFieldImpl();
    return simpleField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SimpleMethod createSimpleMethod()
  {
    SimpleMethodImpl simpleMethod = new SimpleMethodImpl();
    return simpleMethod;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SimpleParam createSimpleParam()
  {
    SimpleParamImpl simpleParam = new SimpleParamImpl();
    return simpleParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SimpleJavaPackage getSimpleJavaPackage()
  {
    return (SimpleJavaPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static SimpleJavaPackage getPackage()
  {
    return SimpleJavaPackage.eINSTANCE;
  }

} //SimpleJavaFactoryImpl
