/*
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.formatting2;

import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.xbase.formatting2.XbaseFormatter;
import org.xtext.simplejava.simpleJava.SimpleClass;
import org.xtext.simplejava.simpleJava.SimpleField;
import org.xtext.simplejava.simpleJava.SimpleMethod;
import org.xtext.simplejava.simpleJava.SimplePackage;

public class SimpleJavaFormatter extends XbaseFormatter {

	protected void format(SimplePackage simplePackage, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (SimpleClass simpleClass : simplePackage.getSimpleClasses()) {
			doc.format(simpleClass);
		}
	}

	protected void format(SimpleClass simpleClass, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (SimpleField simpleField : simpleClass.getSimpleFields()) {
			doc.format(simpleField);
		}
		for (SimpleMethod simpleMethod : simpleClass.getSimpleMethods()) {
			doc.format(simpleMethod);
		}
	}
	
	// TODO: implement for SimpleField, SimpleMethod, SimpleParam
}
