/*
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.simplejava.parser.antlr.internal.InternalSimpleJavaParser;
import org.xtext.simplejava.services.SimpleJavaGrammarAccess;

public class SimpleJavaParser extends AbstractAntlrParser {

	@Inject
	private SimpleJavaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimpleJavaParser createParser(XtextTokenStream stream) {
		return new InternalSimpleJavaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SimplePackage";
	}

	public SimpleJavaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimpleJavaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
