/*
 * generated by Xtext 2.25.0
 */
package org.xtext.simplejava.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.simplejava.SimpleJavaRuntimeModule;
import org.xtext.simplejava.SimpleJavaStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SimpleJavaIdeSetup extends SimpleJavaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SimpleJavaRuntimeModule(), new SimpleJavaIdeModule()));
	}
	
}
